# Copyright (c) 2019-2022, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

# The robot descriptor defines the generalized coordinates and how to map those
# to the underlying URDF dofs.

api_version: 1.0


# Defines the generalized coordinates. Each generalized coordinate is assumed
# to have an entry in the URDF.
# RMPflow will only use these joints to control the robot position.
cspace:
    - Rotation
    - Pitch
    - Elbow
    - Wrist_Pitch
    - Wrist_Roll
    - Jaw


# Global frame of the URDF
root_link: Base

# The default cspace position of this robot
default_q: [
    0.0,0.3,1.2,0.0,0.0,0.0
]

acceleration_limits: [50.0, 50.0, 50.0, 50.0, 50.0, 50.0]
jerk_limits: [10000.0, 10000.0, 10000.0, 10000.0, 10000.0, 10000.0]

# RMPflow uses collision spheres to define the robot geometry in order to avoid
# collisions with external obstacles.  If no spheres are specified, RMPflow will
# not be able to avoid obstacles.  
collision_spheres:
  - Rotation_Pitch:
    - "center": [0.0, 0.08, 0.0]
      "radius": 0.08
  - Upper_Arm:
    - "center": [0.0, 0.025, 0]
      "radius": 0.065
  - Lower_Arm:
    - "center": [0.0, 0.05, 0]
      "radius": 0.055
  - Wrist_Pitch_Roll:
    - "center": [0.0, 0.0, -0.05]
      "radius": 0.05
  - Fixed_Jaw:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.02
  - Moving_Jaw:
    - "center": [0.0, 0.02, 0.0]
      "radius": 0.015
    
# collision_spheres:
#   - Base:
#     - "center": [0.0, 0.0, 0.1]
#       "radius": 0.08
#     # - "center": [0.0, 0.0, 0.15]
#     #   "radius": 0.08
#     # - "center": [0.0, 0.0, 0.2]
#     #   "radius": 0.08
#   - Rotation_Pitch:
#     - "center": [0.0, 0.08, 0.0]
#       "radius": 0.08
#     - "center": [0.0, 0.16, 0.0]
#       "radius": 0.08
#     - "center": [0.0, 0.175, 0.05]
#       "radius": 0.065
#     - "center": [0.0, 0.175, 0.1]
#       "radius": 0.065
#     - "center": [0.0, 0.175, 0.15]
#       "radius": 0.065
#     - "center": [0.0, 0.175, 0.2]
#       "radius": 0.065
#     - "center": [0.0, 0.175, 0.25]
#       "radius": 0.065
#     - "center": [0.0, 0.175, 0.3]
#       "radius": 0.065 
#     - "center": [0.0, 0.175, 0.35]
#       "radius": 0.065
#     - "center": [0.0, 0.175, 0.4]
#       "radius": 0.065 
#     - "center": [0.0, 0.175, 0.45]
#       "radius": 0.065
#     - "center": [0.0, 0.175, 0.5]
#       "radius": 0.065 
#     - "center": [0.0, 0.1, 0.5]
#       "radius": 0.07
#   - Upper_Arm:
#     - "center": [0.0, 0.025, 0]
#       "radius": 0.065
#     - "center": [0.0, -0.025, 0]
#       "radius": 0.065
#     - "center": [0.0, -0.025, 0.05]
#       "radius": 0.065
#     - "center": [0.0, -0.025, 0.1]
#       "radius": 0.065
#     - "center": [0.0, -0.025, 0.15]
#       "radius": 0.06
#     - "center": [0.0, -0.025, 0.2]
#       "radius": 0.06
#     - "center": [0.0, -0.025, 0.25]
#       "radius": 0.06
#     - "center": [0.0, -0.025, 0.3]
#       "radius": 0.06
#     - "center": [0.0, -0.025, 0.35]
#       "radius": 0.055
#     - "center": [0.0, -0.025, 0.4]
#       "radius": 0.055
#   - Lower_Arm:
#     - "center": [0.0, 0.05, 0]
#       "radius": 0.055
#     - "center": [0.0, 0.1, 0]
#       "radius": 0.055
#   - Wrist_Pitch_Roll:
#     - "center": [0.0, 0.0, -0.05]
#       "radius": 0.05
#     - "center": [0.0, 0.0, -0.1]
#       "radius": 0.05
#     - "center": [0.0, 0.0, -0.15]
#       "radius": 0.05
#     - "center": [0.0, 0.0, 0.04]
#       "radius": 0.035
#     - "center": [0.0, 0.0, 0.08]
#       "radius": 0.035
#     - "center": [0.0, 0.0, 0.12]
#       "radius": 0.035
#   - Fixed_Jaw:
#     - "center": [0.0, 0.0, 0.0]
#       "radius": 0.02
#     - "center": [0.0, -0.03, 0.025]
#       "radius": 0.02
#     - "center": [0.0, -0.05, 0.05]
#       "radius": 0.02
#   - Moving_Jaw:
#     - "center": [0.0, 0.02, 0.0]
#       "radius": 0.015
#     - "center": [0.0, 0.02, 0.015]
#       "radius": 0.015
#     - "center": [0.0, 0.02, 0.03]
#       "radius": 0.015
#     - "center": [0.0, 0.025, 0.04]
#       "radius": 0.01